/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.controllerLogin;
import Models.modelEPS;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class formAdmin extends javax.swing.JFrame {

    /**
     * Creates new form formAdmin
     */
    public formAdmin() {
        setIcon();
        initComponents();
        showUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbUser = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnEPS = new javax.swing.JButton();
        btnNewUser = new javax.swing.JButton();
        btnEPS1 = new javax.swing.JButton();
        btnRetiredCyclist = new javax.swing.JButton();
        btnNewUser2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/locked x64.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 60, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabel2.setText("Sección de Administrador");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 600, 10));

        lbUser.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/man-user.png"))); // NOI18N
        lbUser.setText(" narias");
        jPanel1.add(lbUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 120, -1));

        btnCancel.setBackground(new java.awt.Color(102, 0, 0));
        btnCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Salir");
        btnCancel.setBorder(null);
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 100, 30));

        btnEPS.setBackground(new java.awt.Color(0, 102, 51));
        btnEPS.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnEPS.setForeground(new java.awt.Color(255, 255, 255));
        btnEPS.setText("Eliminar EPS");
        btnEPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEPSActionPerformed(evt);
            }
        });
        jPanel1.add(btnEPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 220, 30));

        btnNewUser.setBackground(new java.awt.Color(0, 0, 51));
        btnNewUser.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnNewUser.setForeground(new java.awt.Color(255, 255, 255));
        btnNewUser.setText("Nuevo Usuario");
        btnNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewUserActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 220, 30));

        btnEPS1.setBackground(new java.awt.Color(0, 102, 51));
        btnEPS1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnEPS1.setForeground(new java.awt.Color(255, 255, 255));
        btnEPS1.setText("Nueva EPS");
        btnEPS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEPS1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnEPS1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 220, 30));

        btnRetiredCyclist.setBackground(new java.awt.Color(0, 51, 51));
        btnRetiredCyclist.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnRetiredCyclist.setForeground(new java.awt.Color(255, 255, 255));
        btnRetiredCyclist.setText("Ciclistas Retirados");
        btnRetiredCyclist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetiredCyclistActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetiredCyclist, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 220, 30));

        btnNewUser2.setBackground(new java.awt.Color(0, 0, 51));
        btnNewUser2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnNewUser2.setForeground(new java.awt.Color(255, 255, 255));
        btnNewUser2.setText("Editar Usuario");
        btnNewUser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewUser2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnNewUser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 220, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        formLogin form = new formLogin();
        showForm(form);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnEPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEPSActionPerformed
        formDeleteEPS form = new formDeleteEPS();
        form.setVisible(true);
    }//GEN-LAST:event_btnEPSActionPerformed

    private void btnNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewUserActionPerformed
        formNewUser form = new formNewUser();
        showForm(form);
    }//GEN-LAST:event_btnNewUserActionPerformed

    private void btnEPS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEPS1ActionPerformed
        newEPS eps = new newEPS();
        eps.setVisible(true);
    }//GEN-LAST:event_btnEPS1ActionPerformed

    private void btnRetiredCyclistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiredCyclistActionPerformed
        formDeletedRiders form = new formDeletedRiders();
        showForm(form);
    }//GEN-LAST:event_btnRetiredCyclistActionPerformed

    private void btnNewUser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewUser2ActionPerformed
        formEditUser form = new formEditUser();
        showForm(form);
    }//GEN-LAST:event_btnNewUser2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formAdmin().setVisible(true);
            }
        });
    }
    void showUser(){
        controllerLogin ctrl = new controllerLogin();
        String user = ctrl.getUser();
        lbUser.setText(user);
    }
    void showForm(JFrame form) {
        form.setVisible(true);
        form.setLocationRelativeTo(null);
        this.dispose();
    }
    private void setIcon() {
        Image icon = new ImageIcon(getClass().getResource("../Images/logox100px.png")).getImage();
        setIconImage(icon);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEPS;
    private javax.swing.JButton btnEPS1;
    private javax.swing.JButton btnNewUser;
    private javax.swing.JButton btnNewUser2;
    private javax.swing.JButton btnRetiredCyclist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbUser;
    // End of variables declaration//GEN-END:variables
}
