/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.controllerCategorias;
import Controllers.controllerCiclistas;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.*;

/**
 *
 * @author ADMIN
 */
public class formListar extends javax.swing.JFrame {

    //Global Variables
    DefaultTableModel tableModel;
    String id = "";
    formMessage modal = new formMessage();

    /**
     * Creates new form formDelete
     */
    public formListar() {
        initComponents();
        txtSearch1.requestFocusInWindow();
        showPlaceholder(txtSearch, "Ingrese el nombre o documento del deportista...");
        createColumns();
        fillTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtSearch = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnBack = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lbInscriptionDay = new javax.swing.JLabel();
        lbModality = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        lbBornDay = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        lbBornPlace = new javax.swing.JLabel();
        lbCategory = new javax.swing.JLabel();
        lbNames = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        lbFather = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        lbMother = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        lbRH = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        lbEPS = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        lbTel = new javax.swing.JLabel();
        lbDir = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jLabel26 = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        jSeparator18 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lbSchool = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        lbDoc = new javax.swing.JLabel();
        txtSearch1 = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 102, 153));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 550, 20));

        txtSearch.setToolTipText("Ingrese Tarjeta de Identidad");
        txtSearch.setBorder(null);
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchFocusLost(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 520, 43));

        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 550, 370));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 10, 470));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logox100px.png"))); // NOI18N
        jLabel3.setText("  ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel4.setText("Sección Listar Deportistas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 47, -1, 50));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1250, -1));

        btnBack.setBackground(new java.awt.Color(102, 102, 0));
        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Menu Principal");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 60, 120, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 51));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Modalidad:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 290, 100, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 160, 10));

        lbInscriptionDay.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbInscriptionDay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbInscriptionDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 160, -1));

        lbModality.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbModality.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbModality, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 290, 160, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 310, 160, 10));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 51));
        jLabel16.setText("Fecha Nac:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, -1, -1));

        lbBornDay.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbBornDay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbBornDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, 160, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 340, 160, 10));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 51));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Lugar Nac:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 320, 100, -1));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 340, 160, 10));

        lbBornPlace.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbBornPlace.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbBornPlace, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 320, 160, -1));

        lbCategory.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbCategory.setForeground(new java.awt.Color(0, 0, 102));
        lbCategory.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbCategory.setText("Categoría");
        jPanel1.add(lbCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 160, 180, -1));

        lbNames.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbNames.setForeground(new java.awt.Color(0, 0, 102));
        lbNames.setText("Nombres y Apellidos...");
        jPanel1.add(lbNames, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Información Personal");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 200, -1, 60));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 600, 10));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 51));
        jLabel18.setText("Fecha Inscripción:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 51));
        jLabel19.setText("Documento:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, -1, -1));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 280, 430, 10));

        lbFather.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbFather.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbFather, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 410, 430, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 51));
        jLabel20.setText("Nombre Padre:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 410, -1, -1));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, 430, 10));

        lbMother.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbMother.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbMother, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 440, 430, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 51));
        jLabel21.setText("Nombre Madre:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, -1, -1));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 460, 430, 10));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 51));
        jLabel22.setText("Tipo de Sangre:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 350, -1, -1));

        lbRH.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbRH.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbRH, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, 160, -1));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, 160, 10));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 51));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Dirección");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 540, 100, -1));
        jPanel1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 370, 160, 10));

        lbEPS.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbEPS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbEPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 350, 160, -1));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 600, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Información de Contácto");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, -1, 60));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 51));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("EPS");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 350, 110, -1));
        jPanel1.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 560, 190, 10));

        lbTel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbTel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 540, 190, -1));

        lbDir.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbDir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 540, 190, -1));
        jPanel1.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 560, 190, 10));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 51));
        jLabel26.setText("E-mail:");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 570, 130, -1));

        lbEmail.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 570, 480, -1));
        jPanel1.add(jSeparator18, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 590, 480, 10));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 0, 51));
        jLabel28.setText("Teléfono:");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, 130, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 51));
        jLabel25.setText("Estudios:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, -1, -1));

        lbSchool.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbSchool.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbSchool, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 380, 430, -1));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 400, 430, 10));

        lbDoc.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        lbDoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 260, 430, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1240, 610));

        txtSearch1.setToolTipText("Ingrese Tarjeta de Identidad");
        txtSearch1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 280, 43));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        txtSearch1.requestFocusInWindow();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String text = txtSearch.getText();
        filter(text);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusLost
        showPlaceholder(txtSearch, "Ingrese el nombre o documento del deportista...");
    }//GEN-LAST:event_txtSearchFocusLost

    private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained
        unshowPlaceholder(txtSearch, "Ingrese el nombre o documento del deportista...");
    }//GEN-LAST:event_txtSearchFocusGained

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        formMain form = new formMain();
        this.dispose();
        form.setVisible(true);
        form.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnBackActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        setData();
    }//GEN-LAST:event_tablaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formListar().setVisible(true);
            }
        });
    }
    void createColumns() {
        tableModel = (DefaultTableModel) tabla.getModel();
        tableModel.addColumn("Nombre");
        tableModel.addColumn("Apellido");
        tableModel.addColumn("N° Documento");
        tableModel.addColumn("Categoría");
    }

    void updateRows() {
        int rows = tabla.getRowCount();
        for (int i = rows - 1; i >= 0; i--) {
            tableModel.removeRow(i);
        }
        fillTable();
    }

    void filter(String query) {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(tableModel);
        tabla.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(query));
    }

    void fillTable() {
        controllerCiclistas ctrl = new controllerCiclistas();
        controllerCategorias ctrlCat = new controllerCategorias();
        try {
            ResultSet rs = ctrl.fillTable();
            while (rs.next()) {
                String nombres = rs.getString("nombres");
                String apellidos = rs.getString("apellidos");
                String doc = rs.getString("n_documento");
                String cat = ctrlCat.getCategoria(rs.getString("fecha_nacimiento"));
                String[] row = {nombres, apellidos, doc, cat};
                tableModel.addRow(row);
            }
        } catch (Exception e) {
            System.out.println("Error recorrer array vista: " + e.getMessage());
        }
    }

    void showPlaceholder(JTextField element, String placeholderText) {
        if (element.getText().equals("")) {
            element.setForeground(Color.decode("#818181"));
            element.setText(placeholderText);
        }
    }

    void unshowPlaceholder(JTextField element, String placeholderText) {
        String text = element.getText();
        if (text.equals(placeholderText)) {
            element.setText("");
            element.setForeground(Color.decode("#000000"));
        }
    }

    void setData() {
        int row = tabla.getSelectedRow();
        String doc = tabla.getValueAt(row, 2).toString();
        controllerCiclistas ctrl = new controllerCiclistas();
        ResultSet data = ctrl.selectListar(doc);

        try {
            while (data.next()) {
                String type = "";
                controllerCategorias cats = new controllerCategorias();
                String cat = cats.getCategoria(data.getString("fecha_nacimiento"));
                switch (data.getInt("tipo_documento")){
                    case 0:
                        type = "T.I.";
                        break;
                    case 1:
                        type = "C.C.";
                        break;
                    default:
                        type = "C.E.";
                        break;
                }
                switch (data.getInt("jornada")){
                    case 0:
                        lbSchool.setText("No estudia");
                        break;
                    case 1:
                        lbSchool.setText(data.getString("colegio")+ " - Mañana");
                        break;
                    case 2:
                        lbSchool.setText(data.getString("colegio")+ " - Tarde");
                        break;
                    default:
                        lbSchool.setText(data.getString("colegio")+ " - Noche");
                        break;
                }
                id = data.getString("id");
                lbEPS.setText(data.getString("epsName"));
                lbRH.setText(data.getString("rhName"));
                lbBornDay.setText(data.getString("fecha_nacimiento").replace("-","/"));
                lbBornPlace.setText(data.getString("lugar_nacimiento"));
                lbInscriptionDay.setText(data.getString("fecha_inscripcion").replace("-","/"));
                lbFather.setText(data.getString("nombre_padre"));
                lbMother.setText(data.getString("nombre_madre"));
                lbModality.setText(data.getString("modalidad"));
                lbNames.setText(data.getString("nombres") + " " + data.getString("apellidos"));
                lbDoc.setText(type + " " +data.getString("n_documento"));
                lbDir.setText(data.getString("direccion"));
                lbEmail.setText(data.getString("email"));
                lbTel.setText(data.getString("telefono"));
                lbCategory.setText(cat);
            }
        } catch (Exception e) {
            System.out.println("Error show data form edit " + e.getMessage());
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbBornDay;
    private javax.swing.JLabel lbBornPlace;
    private javax.swing.JLabel lbCategory;
    private javax.swing.JLabel lbDir;
    private javax.swing.JLabel lbDoc;
    private javax.swing.JLabel lbEPS;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbFather;
    private javax.swing.JLabel lbInscriptionDay;
    private javax.swing.JLabel lbModality;
    private javax.swing.JLabel lbMother;
    private javax.swing.JLabel lbNames;
    private javax.swing.JLabel lbRH;
    private javax.swing.JLabel lbSchool;
    private javax.swing.JLabel lbTel;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearch1;
    // End of variables declaration//GEN-END:variables
}
