/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.controllerCategorias;
import Controllers.controllerCiclistas;
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.table.*;

/**
 *
 * @author ADMIN
 */
public class formEdit extends javax.swing.JFrame {

    //Global Variables
    DefaultTableModel tableModel;
    String id = "";

    /**
     * Creates new form formDelete
     */
    public formEdit() {
        initComponents();
        allPlaceholders();
        txtSearch1.requestFocusInWindow();
        createColumns();
        fillTable();
        getEPS();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtSearch = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtColegio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNumeroDoc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        cbxJornada = new javax.swing.JComboBox<>();
        cbxTipo = new javax.swing.JComboBox<>();
        txtApellidos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        btnRetirar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        btnBack = new javax.swing.JButton();
        cbxEPS = new javax.swing.JComboBox<>();
        txtSearch1 = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 102, 153));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 550, 20));

        txtSearch.setToolTipText("Ingrese Tarjeta de Identidad");
        txtSearch.setBorder(null);
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchFocusLost(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        jPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 520, 43));

        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabla);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 550, 330));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Contacto");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 370, -1, -1));

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, 200, -1));

        txtColegio.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtColegio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtColegioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtColegioFocusLost(evt);
            }
        });
        jPanel1.add(txtColegio, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 330, 200, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("EPS");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, 40, -1));

        txtNumeroDoc.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtNumeroDoc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNumeroDocFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumeroDocFocusLost(evt);
            }
        });
        jPanel1.add(txtNumeroDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 290, 200, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Documeto");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Nombres");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 210, -1, -1));

        txtNombres.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtNombres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombresFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombresFocusLost(evt);
            }
        });
        jPanel1.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 210, 320, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Apellidos");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 250, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Dirección");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 410, -1, -1));

        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelefonoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefonoFocusLost(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 370, 110, -1));

        txtDireccion.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDireccionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDireccionFocusLost(evt);
            }
        });
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 410, 320, -1));

        cbxJornada.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cbxJornada.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Mañana", "Tarde", "Noche" }));
        cbxJornada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(cbxJornada, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 330, 110, 24));

        cbxTipo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "T.I.", "C.C.", "C.E." }));
        cbxTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(cbxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 290, 110, 24));

        txtApellidos.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        txtApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtApellidosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidosFocusLost(evt);
            }
        });
        jPanel1.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 320, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Estuduios");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, -1, -1));

        btnUpdate.setText("Actualizar");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 490, 130, -1));

        btnRetirar.setText("Retirar");
        btnRetirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 490, 130, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 10, 430));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logox100px.png"))); // NOI18N
        jLabel3.setText("  ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        jLabel4.setText("Sección Actualizar Información");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 47, -1, 50));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1140, -1));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setText("Menu Principal");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 60, -1, -1));

        cbxEPS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        jPanel1.add(cbxEPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 450, 320, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 570));

        txtSearch1.setToolTipText("Ingrese Tarjeta de Identidad");
        txtSearch1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txtSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 410, 280, 43));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        txtSearch1.requestFocusInWindow();
    }//GEN-LAST:event_jPanel1MouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        String text = txtSearch.getText();
        filter(text);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusLost
        showPlaceholder(txtSearch, "Ingrese el nombre o documento del deportista...");
    }//GEN-LAST:event_txtSearchFocusLost

    private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained
        unshowPlaceholder(txtSearch, "Ingrese el nombre o documento del deportista...");
    }//GEN-LAST:event_txtSearchFocusGained

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
        unshowPlaceholder(txtEmail, "Correo Electrónico");
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        showPlaceholder(txtEmail, "Correo Electrónico");
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtColegioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtColegioFocusGained
        unshowPlaceholder(txtColegio, "Institución Educativa");
    }//GEN-LAST:event_txtColegioFocusGained

    private void txtColegioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtColegioFocusLost
        showPlaceholder(txtColegio, "Institución Educativa");
    }//GEN-LAST:event_txtColegioFocusLost

    private void txtNumeroDocFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroDocFocusGained
        unshowPlaceholder(txtNumeroDoc, "N° de Documento");
    }//GEN-LAST:event_txtNumeroDocFocusGained

    private void txtNumeroDocFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroDocFocusLost
        showPlaceholder(txtNumeroDoc, "N° de Documento");
    }//GEN-LAST:event_txtNumeroDocFocusLost

    private void txtNombresFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombresFocusGained
        unshowPlaceholder(txtNombres, "Nombres");
    }//GEN-LAST:event_txtNombresFocusGained

    private void txtNombresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombresFocusLost
        showPlaceholder(txtNombres, "Nombres");
    }//GEN-LAST:event_txtNombresFocusLost

    private void txtTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoFocusGained
        unshowPlaceholder(txtTelefono, "Teléfono");
    }//GEN-LAST:event_txtTelefonoFocusGained

    private void txtTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoFocusLost
        showPlaceholder(txtTelefono, "Teléfono");
    }//GEN-LAST:event_txtTelefonoFocusLost

    private void txtDireccionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDireccionFocusGained
        unshowPlaceholder(txtDireccion, "Dirección de Residencia");
    }//GEN-LAST:event_txtDireccionFocusGained

    private void txtDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDireccionFocusLost
        showPlaceholder(txtDireccion, "Dirección de Residencia");
    }//GEN-LAST:event_txtDireccionFocusLost

    private void txtApellidosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidosFocusGained
        unshowPlaceholder(txtApellidos, "Apellidos");
    }//GEN-LAST:event_txtApellidosFocusGained

    private void txtApellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidosFocusLost
        showPlaceholder(txtApellidos, "Apellidos");
    }//GEN-LAST:event_txtApellidosFocusLost

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        formMain form = new formMain();
        this.dispose();
        form.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        setData();
    }//GEN-LAST:event_tablaMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        update();
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRetirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarActionPerformed
        delete();
    }//GEN-LAST:event_btnRetirarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formEdit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formEdit().setVisible(true);
            }
        });
    }
    
    void getEPS(){
        controllerCiclistas ctrl = new controllerCiclistas();
        ctrl.getEps();
        ResultSet data = ctrl.getEps();
        try {
            while (data.next()) {
                cbxEPS.addItem(data.getString("nombre"));
            }
        } catch (Exception e) {
            System.out.println("Error loading eps");
        }
    }
    void createColumns() {
        tableModel = (DefaultTableModel) tabla.getModel();
        tableModel.addColumn("Nombre");
        tableModel.addColumn("Apellido");
        tableModel.addColumn("N° Documento");
        tableModel.addColumn("Categoría");
    }
    void updateRows(){
        int rows = tabla.getRowCount();
        for(int i = rows - 1; i >=0; i--){
            tableModel.removeRow(i);
        }
        fillTable();
    }
    void filter(String query) {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(tableModel);
        tabla.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(query));
    }

    void fillTable() {
        controllerCiclistas ctrl = new controllerCiclistas();
        controllerCategorias ctrlCat = new controllerCategorias();
        try {
            ResultSet rs = ctrl.fillTable();
            while (rs.next()) {
                String nombres = rs.getString("nombres");
                String apellidos = rs.getString("apellidos");
                String doc = rs.getString("n_documento");
                String cat = ctrlCat.getCategoria(rs.getString("fecha_nacimiento"));
                String[] row = {nombres,apellidos,doc,cat};
                tableModel.addRow(row);
            }
        } catch (Exception e) {
            System.out.println("Error recorrer array vista: "+ e.getMessage());
        }
    }

    void showPlaceholder(JTextField element, String placeholderText) {
        if (element.getText().equals("")) {
            element.setForeground(Color.decode("#818181"));
            element.setText(placeholderText);
        }
    }
    
    void unshowPlaceholder(JTextField element, String placeholderText) {
        String text = element.getText();
        if (text.equals(placeholderText)) {
            element.setText("");
            element.setForeground(Color.decode("#000000"));
        }
    }
    void allPlaceholders(){
        txtSearch1.requestFocusInWindow();
        showPlaceholder(txtSearch, "Ingrese el nombre o documento del deportista...");
        showPlaceholder(txtNombres, "Nombres");
        showPlaceholder(txtApellidos, "Apellidos");
        showPlaceholder(txtNumeroDoc, "N° de Documento");
        showPlaceholder(txtColegio, "Institución Educativa");
        showPlaceholder(txtDireccion, "Dirección de Residencia");
        showPlaceholder(txtEmail, "Correo Electrónico");
        showPlaceholder(txtTelefono, "Teléfono");
    }
    void unshowAllPlaceholders(){
        unshowPlaceholder(txtNombres, "Nombres");
        unshowPlaceholder(txtApellidos, "Apellidos");
        unshowPlaceholder(txtNumeroDoc, "N° de Documento");
        unshowPlaceholder(txtColegio, "Institución Educativa");
        unshowPlaceholder(txtDireccion, "Dirección de Residencia");
        unshowPlaceholder(txtEmail, "Correo Electrónico");
        unshowPlaceholder(txtTelefono, "Teléfono");
    }
    void setData(){
        int row = tabla.getSelectedRow();
        String doc = tabla.getValueAt(row, 2).toString();
        controllerCiclistas ctrl = new controllerCiclistas();
        ResultSet data = ctrl.selectEdit(doc);
        
        try {
            unshowAllPlaceholders();
            while (data.next()) {
                id = data.getString("id");
                String eps = ctrl.getEps(data.getString("eps"));
                txtNombres.setText(data.getString("nombres"));
                txtApellidos.setText(data.getString("apellidos"));
                txtColegio.setText(data.getString("colegio"));
                txtNumeroDoc.setText(data.getString("n_documento"));
                cbxEPS.setSelectedItem(eps);
                txtDireccion.setText(data.getString("direccion"));
                txtEmail.setText(data.getString("email"));
                txtTelefono.setText(data.getString("telefono"));
                cbxTipo.setSelectedIndex(data.getInt("tipo_documento"));
                cbxJornada.setSelectedIndex(data.getInt("jornada"));
            }
        } catch (Exception e) {
            System.out.println("Error show data form edit " + e.getMessage());
        }
        
    }
    void update(){
        controllerCiclistas ctrl = new controllerCiclistas();
        String doc =txtNumeroDoc.getText();
        int type = cbxTipo.getSelectedIndex();
        String col = txtColegio.getText();
        String mail = txtEmail.getText();
        String nombres = txtNombres.getText();
        String apellidos = txtApellidos.getText();
        String tel = txtTelefono.getText();
        int eps = ctrl.getID(cbxEPS.getSelectedItem().toString(), "eps");
        int jor = cbxJornada.getSelectedIndex();
        String dir = txtDireccion.getText();
        Object[] data = {id,doc,type,nombres,apellidos,col,jor,mail,tel,dir,eps};
        ctrl.update(data);
        updateRows();
    }
    void delete(){
        controllerCiclistas ctrl = new controllerCiclistas();
        ctrl.delete(id);
        updateRows();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRetirar;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbxEPS;
    private javax.swing.JComboBox<String> cbxJornada;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtColegio;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNumeroDoc;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearch1;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
